version: '3.8'

services:
  crane-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"  # Frontend dev server
      - "8080:8080"  # Backend WebSocket server
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - frontend_node_modules:/app/frontend/node_modules
      - backend_node_modules:/app/backend/node_modules
      - shared_node_modules:/app/packages/shared/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  node_modules:
  frontend_node_modules:
  backend_node_modules:
  shared_node_modules: